### ISSUE TITLE
Lists missing

### ISSUE THREAD

**Issue by pallebone** [complexorganizations/content-blocker#24]
Hi,

I was testing these lists but today they are all 404.

EG:
https://raw.githubusercontent.com/complexorganizations/content-blocker/main/configs/hosts

No longer exists?

Kind regards
Pete

**Comment by Prajwal-Koirala** [comment]
New lists will be available in the next 24 hours, since they are so large git wasn't able to support them.

**Comment by pallebone** [comment]
What kind of resources?

**Comment by Prajwal-Koirala** [comment]
Mostly CPU, some bandwidth (5GB), and storage (1 GB)

**Comment by pallebone** [comment]
I can host but cpu is limited on the cloud instance I use. Probably better to just ftp up any files you want hosted and compute locally on your pc. It will be faster.

**Comment by Prajwal-Koirala** [comment]
Hey, it's going to take a couple of hours for it to update but it's fine, Its not the hosting that's the issue the hosting is fine, it's just that generating the list takes too long and too much system resources

**Comment by pallebone** [comment]
Ok if you change your mind and need a place to put files in the cloud let me know and I can setup an ftp account for you.

**Comment by Prajwal-Koirala** [comment]
It's okay, thanks tho.

I don't need storage I need CPU resources to find more lists and than validate those lists.

**Comment by pallebone** [comment]
Ok. Sorry I dont have that. Hope you can find a solution.

**Comment by Saugjunkie** [comment]
for few days, you can use my vserver for this

**Comment by Prajwal-Koirala** [comment]
> for few days, you can use my vserver for this

Its okay thank you, i have tried cloud servers and bare metal servers, but the issue is that it wont be able to handle the load.

**Comment by Saugjunkie** [comment]
hmm okay, i still sent you the server data to protonmail.com just try it out

**Comment by Prajwal-Koirala** [comment]
> hmm okay, i still sent you the server data to protonmail.com just try it out

Its okay thank you, i don't need it.

See the issue right now is that there are over 5 Million domains on my lists, it can take up to a week to validate them all slowly 1 by 1 or i have the option to validate them super fast and it requires a lot of system resources, just need to figure out a way to validate it super fast without using alot of system resources and we are good.

**Comment by Saugjunkie** [comment]
why all at once in one big list? Do you just make several smaller ones and divide them up on several servers? Surely that only has to be done once and some are duplicated.

In the first round a file with 1,000,000 entries, all that remains, merge and divide again, check merge.

**Comment by Prajwal-Koirala** [comment]
> why all at once in one big list? Do you just make several smaller ones and divide them up on several servers? Surely that only has to be done once and some are duplicated.
> 
> In the first round a file with 1,000,000 entries, all that remains, merge and divide again, check merge.

This is one of the options i have thought of but i know if i work on it a bit more, i can make a single automated system that will do this every 24 hours.

Once i get this pr to fix the issue, it will be able to validate 20M domains easily under 2 hours.

https://github.com/complexorganizations/content-blocker/pull/26

**Comment by pallebone** [comment]
Just fyi some malicious domains come online only when a scam is running eg: scammers turn on the webserver then disable them again to be used again in the future so validating they are online can be a negative consequence of removing domains not always online but should be blocked.

**Comment by Prajwal-Koirala** [comment]
> Just fyi some malicious domains come online only when a scam is running eg: scammers turn on the webserver then disable them again to be used again in the future so validating they are online can be a negative consequence of removing domains not always online but should be blocked.

Yeah, i check if the domain is registered or not, that's what i consider validation.

if there is even 0.01% proof that its registered than its a valid domain.

**Comment by pallebone** [comment]
Ok makes sense.

**Comment by Prajwal-Koirala** [comment]
Stevenhost is one of the most popular lists I'm aware of, and they contain a handful of domains that don't make any sense.
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
`0.0.0.0 castoola.tv.lan` Even if it isn't a genuine domain, it is still on the list.

**Comment by pallebone** [comment]
As no further discussion warranted I am closing this issue to tidy up.

**Comment by Prajwal-Koirala** [comment]
@pallebone
I am going to push unvalidated data and than work on this, and than once its ready i will push the validated data.

**Comment by Prajwal-Koirala** [comment]
@pallebone
@Saugjunkie

The temp lists are ready, this is the biggest lists on github that i know of, the official lists contains over 5 mil valid domains, but these are temp update.

**Comment by Prajwal-Koirala** [comment]
For now import it on unblock origin, and will push a fix for coredns

**Comment by Saugjunkie** [comment]
> 
> 
> For now import it on unblock origin, and will push a fix for coredns

Unfortunately, I didn't understand that despite the Google translation

**Comment by Prajwal-Koirala** [comment]
https://github.com/gorhill/uBlock

**Comment by Prajwal-Koirala** [comment]
My lads, I finally got it working on a digitalocean vps with 64 GB memory and 32 cores.

**Comment by pallebone** [comment]
good job. sounds expensive though :(

**Comment by Prajwal-Koirala** [comment]
> good job. sounds expensive though :(

It costs around $1 per hour, and updating the list takes about an hour, so over the course of a month, it costs about $30, which is good.

**Comment by Prajwal-Koirala** [comment]
Guys, it works now and pushes a update every 24 hours.

**Comment by Prajwal-Koirala** [comment]
Guys, it works now and pushes a update every 24 hours.

**Comment by Saugjunkie** [comment]
> 
> 
> Guys, it works now and pushes a update every 24 hours.

Good News

THX @Prajwal-Koirala
