### ISSUE TITLE
IPV6 long time to load

### ISSUE THREAD

**Issue by Saugjunkie** [complexorganizations/content-blocker#59]
We need to talk about IPV6. I noticed that when you use both IPV4 and IPV6.
In dual stack operation, loading times take a long time when a website tries to load blocked content.
If you only use IPV4, you don't have these problems and the loading time of a website with blocked content is very fast.

**Comment by Prajwal-Koirala** [comment]
What do u mean?
Please explain

**Comment by Saugjunkie** [comment]
yesterday i have post the load speed from emailn.de one was very long loadtime and the another was very fast. The very fast load speed have not use ipv6, only IPV4  for client and dns server was activate.
Today i have new install with actually wireguard and content blocker while i have forget activate IPV6 and now the loadtime is again very long for it. 
Than i have look at the hosts.conf in /etc/unbound... and i have see inside only "IN A 0.0.0.0" for domains but not "IN AAA  ::" for IPV6.

**Comment by Prajwal-Koirala** [comment]
Can u please post your changed and remove any IP and any keys from it

**Comment by Prajwal-Koirala** [comment]
Hey,
Run the wireguard manager script first, then udate, and it will self-correct.

**Comment by Saugjunkie** [comment]
/usr/local/bin/wireguard-manager.sh: Zeile 1621: Syntaxfehler beim unerwarteten Wort `fi'
/usr/local/bin/wireguard-manager.sh: Zeile 1621: `fi'
root@main:~#

**Comment by Prajwal-Koirala** [comment]
> /usr/local/bin/wireguard-manager.sh: Zeile 1621: Syntaxfehler beim unerwarteten Wort `fi' /usr/local/bin/wireguard-manager.sh: Zeile 1621: `fi'
> root@main:~#

Update again.
